### ISSUE TITLE
How it works ?

### ISSUE THREAD

**Issue by Jer3m** [Que20/homebridge-freebox-player#1]
Hello,

I have Freebox revolution and I will be interrested by trying your plugin, but I didn't get how it works.
I already have Freemote plugin, do I have to delete it and paste .json into yours ?

**Comment by Que20** [comment]
Hi Jer3m.
This project is no longer maintained. It hase been moved to [fbx/homebridge-freebox-home/](https://github.com/fbx/homebridge-freebox-home/).

The homebridge-freebox-home server works only as a compatibly bridge for the Freebox Delta's security module.

**Comment by Que20** [comment]
Hello Jer3m,
This code does not work properly yet. I would not encourage anyone using it.
Anyway the plugin is meant to be used as a platform with the name `homebridge-freebox-player` in homebridge.

**Comment by Jer3m** [comment]
Thanks for answer.
Any chances to get something as remote control working with the Freebox revolution?

**Comment by Que20** [comment]
Yes I might work on it later this year. Eventually it'll be on the official fbx repo.

**Comment by Jer3m** [comment]
I will check.

Thanks
